language: csharp
solution: "./Fibonacci/Fibonacci.sln"
install:
- travis_retry nuget restore -source "https://www.nuget.org/api/v2" ./Fibonacci/Fibonacci.sln
script:
- xbuild ./Fibonacci/Fibonacci.sln
- mono ./Fibonacci/packages/xunit.runner.console*/tools/xunit.console.exe ./Fibonacci/Fibonacci.Tests/bin/Debug/Fibonacci.Tests.dll
